name: 'build and test Python code'

on:

  workflow_dispatch:  # manual triggering

  push:
    paths:
      - '.github/workflows/build_python.yaml'
      - '.coveragerc'
      - 'requirements.txt'
      - 'memvid/**'
      - 'tests/**'

jobs:

  build_python:

    runs-on: ubuntu-latest

    timeout-minutes: 45

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:

    - name: checkout code from repo
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: prelude
      run: |
          python --version

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade pytest

    - name: checking syntax of scripts
      run: |
        python -m py_compile $(git ls-files '*.py')

    - name: Running all tests
      run: |
        export PYTHONPATH="$(pwd)/memvid:$(pwd)/tests":$PYTHONPATH
        echo "PYTHONPATH:" $PYTHONPATH
        #
        pytest $(pwd)